version: '3.8'

services:
  # Aplicação Principal VORIXA (Next.js 16 Standalone)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vorixa-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3005:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://vorixa_user:vorixa_password@postgres:5432/vorixa_db?schema=public
      - AUTH_SECRET=${AUTH_SECRET:-change_in_production_secret_key_vorixa_2026}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://vortixia.com.br}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://vortixia.com.br}
      - AI_PROVIDER_MODE=${AI_PROVIDER_MODE:-live}
      - FAL_KEY=${FAL_KEY:-b853f917-5e92-4d12-bf3e-a09dba498291:a78de2b18ba9d65b4f8f881df4b5a6c3}
      - PAYMENT_PROVIDER=${PAYMENT_PROVIDER:-mock_gateway}
      - PAYMENT_PROVIDER_MODE=${PAYMENT_PROVIDER_MODE:-mock}
      - SMTP_HOST=${SMTP_HOST:-smtp.hostinger.com}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_USER=${SMTP_USER:-contato@vortixia.com.br}
      - SMTP_PASS=${SMTP_PASS:-Admin@212121@}
      - SMTP_FROM=${SMTP_FROM:-contato@vortixia.com.br}
      - SMTP_SENDER_NAME=${SMTP_SENDER_NAME:-VORIXA AI}
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - vorixa-uploads:/app/public/uploads
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - vorixa-network

  # Banco de Dados Relacional PostgreSQL 15 com Volume Persistente
  postgres:
    image: postgres:15-alpine
    container_name: vorixa-postgres
    restart: always
    environment:
      POSTGRES_USER: vorixa_user
      POSTGRES_PASSWORD: vorixa_password
      POSTGRES_DB: vorixa_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - vorixa-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vorixa_user -d vorixa_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vorixa-network

  # Object Storage S3 Compatível Local (MinIO)
  minio:
    image: minio/minio
    container_name: vorixa-minio
    restart: always
    ports:
      - "127.0.0.1:9010:9000"
      - "127.0.0.1:9011:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - vorixa-minio-data:/data
    networks:
      - vorixa-network

volumes:
  vorixa-postgres-data:
    external: true
    name: vorixa_vorixa-postgres-data
  vorixa-minio-data:
    external: true
    name: vorixa_vorixa-minio-data
  vorixa-uploads:
    driver: local

networks:
  vorixa-network:
    driver: bridge
