version: '3.8'

services:
  # Aplicação Principal VORIXA (Next.js 16 Standalone)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vorixa-app
    restart: unless-stopped
    ports:
      - 127.0.0.1:3005:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=https://vortixia.com.br
      - NEXT_PUBLIC_APP_URL=https://vortixia.com.br
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - vorixa-network

  # Banco de Dados Relacional PostgreSQL 15 (ISOLADO NA REDE INTERNA)
  postgres:
    image: postgres:15-alpine
    container_name: vorixa-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - vorixa-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vorixa_user -d vorixa_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vorixa-network

  # Object Storage S3 Compatível Local (MinIO)
  minio:
    image: minio/minio
    container_name: vorixa-minio
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:9010:9000"
      - "127.0.0.1:9011:9001"
    command: server /data --console-address :9001
    volumes:
      - vorixa-minio-data:/data
    networks:
      - vorixa-network

volumes:
  vorixa-postgres-data:
    driver: local
  vorixa-minio-data:
    driver: local

networks:
  vorixa-network:
    driver: bridge
